server:
  port: @service.port@
spring:
  boot:
    enableautoconfiguration: true
  # redis
  datasource:
    driver-class-name: @spring.datasource.driver@
    username: @spring.datasource.username@
    password: @spring.datasource.password@
    url: @spring.datasource.url@
  redis:
    host: @redis.datasource.host@
    port: @redis.datasource.port@
    timeout: 3
    password: @redis.datasource.password@
    lettuce:
      pool:
        max-active: 8
        max-wait: 3
        max-idle: 10
        min-idle: 1
  aop:
    auto: true
    proxy-target-class: true
mybatis:
  configuration-properties: